
export const enum Commands {
  config_locales_auto = 'i18n-ally.config-locales-auto',
  config_display_language = 'i18n-ally.config-display-language',
  config_source_language = 'i18n-ally.config-source-language',
  config_locales = 'i18n-ally.config-locales',
  set_display_language = 'i18n-ally.set-display-language',
  set_source_language = 'i18n-ally.set-source-language',
  extract_text = 'i18n-ally.extract-text',
  copy_key = 'i18n-ally.copy-key',
  translate_key = 'i18n-ally.translate-key',
  edit_key = 'i18n-ally.edit-key',
  open_key = 'i18n-ally.open-key',
  delete_key = 'i18n-ally.delete-key',
  rename_key = 'i18n-ally.rename-key',
  new_key = 'i18n-ally.new-key',
  insert_key = 'i18n-ally.insert-key',
  duplicate_key = 'i18n-ally.duplicate-key',
  fulfill_keys = 'i18n-ally.fulfill-keys',
  locale_visibility_toggle = 'i18n-ally.locale-visibility-toggle',
  locale_visibility_show = 'i18n-ally.locale-visibility-show',
  locale_visibility_hide = 'i18n-ally.locale-visibility-hide',
  open_url = 'i18n-ally.open-url',
  support = 'i18n-ally.support',
  refresh_usage = 'i18n-ally.refresh-usage',
  mark_key_as_in_use = 'i18n-ally.mark-key-as-in-use',
  open_in_editor = 'i18n-ally.open-in-editor',
  open_editor = 'i18n-ally.open-editor',
  review_comment = 'i18n-ally.review.comment',
  review_approve = 'i18n-ally.review.approve',
  review_request_change = 'i18n-ally.review.request-change',
  review_edit = 'i18n-ally.review.edit',
  review_resolve = 'i18n-ally.review.resolve',
  review_resolve_thread = 'i18n-ally.review.resolve-thread',
  review_refresh_thread = 'i18n-ally.review.refresh-thread',
  review_apply_translation = 'i18n-ally.review.apply-translation',
  review_apply_suggestion = 'i18n-ally.review.apply-suggestion',
}
