
export const enum Commands {
  config_locales_auto = 'extension.i18n-ally.config-locales-auto',
  config_display_language = 'extension.i18n-ally.config-display-language',
  config_source_language = 'extension.i18n-ally.config-source-language',
  config_locales = 'extension.i18n-ally.config-locales',
  set_display_language = 'extension.i18n-ally.set-display-language',
  set_source_language = 'extension.i18n-ally.set-source-language',
  extract_text = 'extension.i18n-ally.extract-text',
  copy_key = 'extension.i18n-ally.copy-key',
  translate_key = 'extension.i18n-ally.translate-key',
  edit_key = 'extension.i18n-ally.edit-key',
  open_key = 'extension.i18n-ally.open-key',
  delete_key = 'extension.i18n-ally.delete-key',
  rename_key = 'extension.i18n-ally.rename-key',
  new_key = 'extension.i18n-ally.new-key',
  duplicate_key = 'extension.i18n-ally.duplicate-key',
  fulfill_keys = 'extension.i18n-ally.fulfill-keys',
  locale_visibility_toggle = 'extension.i18n-ally.locale-visibility-toggle',
  locale_visibility_show = 'extension.i18n-ally.locale-visibility-show',
  locale_visibility_hide = 'extension.i18n-ally.locale-visibility-hide',
  open_url = 'extension.i18n-ally.open-url',
  support = 'extension.i18n-ally.support',
  refresh_usage = 'extension.i18n-ally.refresh-usage',
  mark_key_as_in_use = 'extension.i18n-ally.mark-key-as-in-use',
  open_in_editor = 'extension.i18n-ally.open-in-editor',
}
