export const EXT_NAMESPACE = 'i18n-ally'
export const EXT_LEGACY_NAMESPACE = 'vue-i18n-ally'
export const EXT_ID = 'antfu.i18n-ally'
export const EXT_LEGACY_ID = 'antfu.vue-i18n-ally'
export const EXT_NAME = 'i18n Ally'
